# Logstash Configuration - SNMP Polling + Traps
# Pipeline definitions are in pipelines.yml
api.http.host: "0.0.0.0"
api.http.port: 9600
xpack.monitoring.enabled: false
log.level: info
log.format: plain
queue.type: memory
queue.max_bytes: 1gb
config.reload.automatic: false
config.reload.interval: 30s
monitoring.cluster_uuid: PRODUCTION_ES_CLUSTER_UUID
